[package]
name = "etradeTaxReturnHelper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdf = "0.7.2"
chrono = "0.4"
reqwest = { version = "0.11.9", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
syslog = "6.0.1"
log = "0.4.0"
clap = "~2.27.0"
